name: pr-check

on:
  pull_request_target:
  
jobs:
   test:
     environment: test
     runs-on: ubuntu-latest
     steps:  
     - name: Checkout from PR branch  
       uses: actions/checkout@v4
       with: 
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
  
     - name: Get the current commit SHA  
       id: get_commit_sha  
       run: echo "Commit SHA $(git rev-parse HEAD)"  
